-- Seed data for ops.* — generated from real Critical-risk customers in
-- <CATALOG>.telcoabc_retention.gold_churn_risk_scores. Notes mention the
-- actual competitor threatening each account (searchable via Lakebase Search).
TRUNCATE ops.offers_presented, ops.case_notes, ops.retention_cases, ops.agents RESTART IDENTITY CASCADE;

INSERT INTO ops.agents (agent_id, agent_name, team, tier) VALUES
  ('AGT-0001','Allison Hill','Team B','Top Performer'),
  ('AGT-0002','Noah Rhodes','Team C','Top Performer'),
  ('AGT-0003','Angie Henderson','Team D','Top Performer'),
  ('AGT-0004','Daniel Wagner','Team E','Top Performer'),
  ('AGT-0005','Cristian Santos','Team F','Top Performer'),
  ('AGT-0006','Connie Lawrence','Team G','Top Performer'),
  ('AGT-0007','Abigail Shaffer','Team H','Top Performer'),
  ('AGT-0008','Gina Moore','Team I','Top Performer');

INSERT INTO ops.retention_cases (customer_id, market, competitor_id, assigned_agent_id, status, priority, recommended_offer_id, opened_at, closed_at, updated_at) VALUES
  ('CUST-010083','Columbus','COMP-01','AGT-0001','Open','Critical','OFF-01', now() - interval '18 days', NULL, now()),
  ('CUST-041805','Austin','COMP-02','AGT-0002','Saved','Critical','OFF-03', now() - interval '7 days', now() - interval '2 days', now()),
  ('CUST-039019','St. Louis','COMP-01','AGT-0003','Open','Critical','OFF-01', now() - interval '3 days', NULL, now()),
  ('CUST-034717','Columbus','COMP-02','AGT-0004','Open','Critical','OFF-03', now() - interval '18 days', NULL, now()),
  ('CUST-043092','Denver','COMP-02','AGT-0005','Open','Critical','OFF-03', now() - interval '15 days', NULL, now()),
  ('CUST-020562','Denver','COMP-01','AGT-0006','Open','Critical','OFF-01', now() - interval '8 days', NULL, now()),
  ('CUST-030255','Dallas','COMP-02','AGT-0007','Saved','Critical','OFF-03', now() - interval '16 days', now() - interval '2 days', now()),
  ('CUST-044435','Denver','COMP-04','AGT-0008','Open','Critical','OFF-04', now() - interval '10 days', NULL, now()),
  ('CUST-039060','New York','COMP-01','AGT-0001','Open','Critical','OFF-01', now() - interval '6 days', NULL, now()),
  ('CUST-044106','Denver','COMP-01','AGT-0002','Open','Critical','OFF-01', now() - interval '3 days', NULL, now()),
  ('CUST-001320','Dallas','COMP-03','AGT-0003','Churned','Critical','OFF-01', now() - interval '16 days', now() - interval '2 days', now()),
  ('CUST-049659','Milwaukee','COMP-01','AGT-0004','Open','Critical','OFF-01', now() - interval '9 days', NULL, now()),
  ('CUST-044914','New York','COMP-01','AGT-0005','In Progress','Critical','OFF-01', now() - interval '10 days', NULL, now()),
  ('CUST-049396','Austin','COMP-04','AGT-0006','Open','Critical','OFF-04', now() - interval '13 days', NULL, now()),
  ('CUST-017283','Los Angeles','COMP-06','AGT-0007','Churned','Critical','OFF-01', now() - interval '20 days', now() - interval '2 days', now()),
  ('CUST-034479','Los Angeles','COMP-01','AGT-0008','Open','Critical','OFF-01', now() - interval '2 days', NULL, now()),
  ('CUST-047411','Denver','COMP-06','AGT-0001','In Progress','Critical','OFF-01', now() - interval '8 days', NULL, now()),
  ('CUST-029506','Columbus','COMP-05','AGT-0002','Saved','Critical','OFF-01', now() - interval '3 days', now() - interval '2 days', now()),
  ('CUST-032412','Dallas','COMP-02','AGT-0003','In Progress','Critical','OFF-03', now() - interval '13 days', NULL, now()),
  ('CUST-007485','Cincinnati','COMP-02','AGT-0004','In Progress','Critical','OFF-03', now() - interval '18 days', NULL, now()),
  ('CUST-049957','New York','COMP-05','AGT-0005','Open','Critical','OFF-01', now() - interval '12 days', NULL, now()),
  ('CUST-020803','Charlotte','COMP-01','AGT-0006','Saved','Critical','OFF-01', now() - interval '5 days', now() - interval '2 days', now()),
  ('CUST-031663','St. Louis','COMP-01','AGT-0007','Open','Critical','OFF-01', now() - interval '8 days', NULL, now()),
  ('CUST-020510','Milwaukee','COMP-01','AGT-0008','In Progress','Critical','OFF-01', now() - interval '6 days', NULL, now()),
  ('CUST-007196','Tampa','COMP-05','AGT-0001','Churned','Critical','OFF-01', now() - interval '5 days', now() - interval '2 days', now()),
  ('CUST-016880','Denver','COMP-03','AGT-0002','Open','Critical','OFF-01', now() - interval '20 days', NULL, now()),
  ('CUST-031572','Cincinnati','COMP-01','AGT-0003','Open','Critical','OFF-01', now() - interval '20 days', NULL, now()),
  ('CUST-006678','St. Louis','COMP-05','AGT-0004','Open','Critical','OFF-01', now() - interval '18 days', NULL, now()),
  ('CUST-023383','Kansas City','COMP-01','AGT-0005','Saved','Critical','OFF-01', now() - interval '16 days', now() - interval '2 days', now()),
  ('CUST-009675','New York','COMP-03','AGT-0006','Open','Critical','OFF-01', now() - interval '3 days', NULL, now()),
  ('CUST-005373','Austin','COMP-01','AGT-0007','In Progress','Critical','OFF-01', now() - interval '11 days', NULL, now()),
  ('CUST-042968','Milwaukee','COMP-02','AGT-0008','Churned','Critical','OFF-03', now() - interval '1 days', now() - interval '2 days', now()),
  ('CUST-036511','Los Angeles','COMP-03','AGT-0001','In Progress','Critical','OFF-01', now() - interval '4 days', NULL, now()),
  ('CUST-000432','Tampa','COMP-05','AGT-0002','Open','Critical','OFF-01', now() - interval '3 days', NULL, now()),
  ('CUST-019443','Austin','COMP-03','AGT-0003','Saved','Critical','OFF-01', now() - interval '9 days', now() - interval '2 days', now()),
  ('CUST-021883','Los Angeles','COMP-01','AGT-0004','Open','Critical','OFF-01', now() - interval '16 days', NULL, now()),
  ('CUST-043572','Milwaukee','COMP-02','AGT-0005','Open','Critical','OFF-03', now() - interval '15 days', NULL, now()),
  ('CUST-033530','Austin','COMP-02','AGT-0006','In Progress','Critical','OFF-03', now() - interval '4 days', NULL, now()),
  ('CUST-040919','Los Angeles','COMP-01','AGT-0007','Open','Critical','OFF-01', now() - interval '16 days', NULL, now()),
  ('CUST-006043','Cincinnati','COMP-03','AGT-0008','Open','Critical','OFF-01', now() - interval '17 days', NULL, now());

INSERT INTO ops.case_notes (case_id, agent_id, note_text) VALUES
  (1, 'AGT-0001', 'Customer called ready to cancel — T-Mobile Home Internet is quoting a comparable plan for less. Very price-sensitive after last bill increase; wants a match or they port out.'),
  (2, 'AGT-0002', 'Customer called ready to cancel — AT&T Fiber is quoting a comparable plan for less. Very price-sensitive after last bill increase; wants a match or they port out.'),
  (2, 'AGT-0002', 'Cord-cutting conversation — wants internet-only. Saw a AT&T Fiber bundle ad. Considering the offer we presented.'),
  (3, 'AGT-0003', 'Cord-cutting conversation — wants internet-only. Saw a T-Mobile Home Internet bundle ad. Considering the offer we presented.'),
  (4, 'AGT-0004', 'Second call this month about pricing. Mentioned AT&T Fiber promo pricing twice. High flight risk; needs a proactive save offer.'),
  (4, 'AGT-0004', 'Retention call. Customer actively comparing us to AT&T Fiber. Loyal but frustrated with speed; open to a 12-month promo if we beat AT&T Fiber.'),
  (5, 'AGT-0005', 'Retention call. Customer actively comparing us to AT&T Fiber. Loyal but frustrated with speed; open to a 12-month promo if we beat AT&T Fiber.'),
  (5, 'AGT-0005', 'Escalation: repeated outages last month. Says AT&T Fiber ''never goes down'' in their neighborhood. Threatening to switch this week.'),
  (6, 'AGT-0006', 'Cord-cutting conversation — wants internet-only. Saw a T-Mobile Home Internet bundle ad. Considering the offer we presented.'),
  (7, 'AGT-0007', 'Customer''s spouse works from home; AT&T Fiber pitched a work-from-home tier. Wants reliability guarantees before renewing.'),
  (7, 'AGT-0007', 'Moving to a new address and already checked AT&T Fiber availability there. Asked what we can do to keep the account.'),
  (8, 'AGT-0008', 'Customer called ready to cancel — Frontier Fiber is quoting a comparable plan for less. Very price-sensitive after last bill increase; wants a match or they port out.'),
  (9, 'AGT-0001', 'Escalation: repeated outages last month. Says T-Mobile Home Internet ''never goes down'' in their neighborhood. Threatening to switch this week.'),
  (9, 'AGT-0001', 'Moving to a new address and already checked T-Mobile Home Internet availability there. Asked what we can do to keep the account.'),
  (10, 'AGT-0002', 'Retention call. Customer actively comparing us to T-Mobile Home Internet. Loyal but frustrated with speed; open to a 12-month promo if we beat T-Mobile Home Internet.'),
  (10, 'AGT-0002', 'Customer''s spouse works from home; T-Mobile Home Internet pitched a work-from-home tier. Wants reliability guarantees before renewing.'),
  (11, 'AGT-0003', 'Customer called ready to cancel — Verizon 5G Home is quoting a comparable plan for less. Very price-sensitive after last bill increase; wants a match or they port out.'),
  (11, 'AGT-0003', 'Second call this month about pricing. Mentioned Verizon 5G Home promo pricing twice. High flight risk; needs a proactive save offer.'),
  (12, 'AGT-0004', 'Customer''s spouse works from home; T-Mobile Home Internet pitched a work-from-home tier. Wants reliability guarantees before renewing.'),
  (12, 'AGT-0004', 'Second call this month about pricing. Mentioned T-Mobile Home Internet promo pricing twice. High flight risk; needs a proactive save offer.'),
  (13, 'AGT-0005', 'Retention call. Customer actively comparing us to T-Mobile Home Internet. Loyal but frustrated with speed; open to a 12-month promo if we beat T-Mobile Home Internet.'),
  (13, 'AGT-0005', 'Customer''s spouse works from home; T-Mobile Home Internet pitched a work-from-home tier. Wants reliability guarantees before renewing.'),
  (14, 'AGT-0006', 'Customer called ready to cancel — Frontier Fiber is quoting a comparable plan for less. Very price-sensitive after last bill increase; wants a match or they port out.'),
  (14, 'AGT-0006', 'Moving to a new address and already checked Frontier Fiber availability there. Asked what we can do to keep the account.'),
  (15, 'AGT-0007', 'Moving to a new address and already checked Verizon Fios availability there. Asked what we can do to keep the account.'),
  (16, 'AGT-0008', 'Second call this month about pricing. Mentioned T-Mobile Home Internet promo pricing twice. High flight risk; needs a proactive save offer.'),
  (17, 'AGT-0001', 'Moving to a new address and already checked Verizon Fios availability there. Asked what we can do to keep the account.'),
  (17, 'AGT-0001', 'Second call this month about pricing. Mentioned Verizon Fios promo pricing twice. High flight risk; needs a proactive save offer.'),
  (18, 'AGT-0002', 'Moving to a new address and already checked Google Fiber availability there. Asked what we can do to keep the account.'),
  (19, 'AGT-0003', 'Escalation: repeated outages last month. Says AT&T Fiber ''never goes down'' in their neighborhood. Threatening to switch this week.'),
  (19, 'AGT-0003', 'Moving to a new address and already checked AT&T Fiber availability there. Asked what we can do to keep the account.'),
  (20, 'AGT-0004', 'Customer''s spouse works from home; AT&T Fiber pitched a work-from-home tier. Wants reliability guarantees before renewing.'),
  (20, 'AGT-0004', 'Moving to a new address and already checked AT&T Fiber availability there. Asked what we can do to keep the account.'),
  (21, 'AGT-0005', 'Escalation: repeated outages last month. Says Google Fiber ''never goes down'' in their neighborhood. Threatening to switch this week.'),
  (21, 'AGT-0005', 'Second call this month about pricing. Mentioned Google Fiber promo pricing twice. High flight risk; needs a proactive save offer.'),
  (22, 'AGT-0006', 'Customer''s spouse works from home; T-Mobile Home Internet pitched a work-from-home tier. Wants reliability guarantees before renewing.'),
  (23, 'AGT-0007', 'Moving to a new address and already checked T-Mobile Home Internet availability there. Asked what we can do to keep the account.'),
  (24, 'AGT-0008', 'Retention call. Customer actively comparing us to T-Mobile Home Internet. Loyal but frustrated with speed; open to a 12-month promo if we beat T-Mobile Home Internet.'),
  (24, 'AGT-0008', 'Customer called ready to cancel — T-Mobile Home Internet is quoting a comparable plan for less. Very price-sensitive after last bill increase; wants a match or they port out.'),
  (25, 'AGT-0001', 'Cord-cutting conversation — wants internet-only. Saw a Google Fiber bundle ad. Considering the offer we presented.'),
  (25, 'AGT-0001', 'Retention call. Customer actively comparing us to Google Fiber. Loyal but frustrated with speed; open to a 12-month promo if we beat Google Fiber.'),
  (26, 'AGT-0002', 'Escalation: repeated outages last month. Says Verizon 5G Home ''never goes down'' in their neighborhood. Threatening to switch this week.'),
  (26, 'AGT-0002', 'Customer''s spouse works from home; Verizon 5G Home pitched a work-from-home tier. Wants reliability guarantees before renewing.'),
  (27, 'AGT-0003', 'Moving to a new address and already checked T-Mobile Home Internet availability there. Asked what we can do to keep the account.'),
  (28, 'AGT-0004', 'Moving to a new address and already checked Google Fiber availability there. Asked what we can do to keep the account.'),
  (28, 'AGT-0004', 'Second call this month about pricing. Mentioned Google Fiber promo pricing twice. High flight risk; needs a proactive save offer.'),
  (29, 'AGT-0005', 'Customer called ready to cancel — T-Mobile Home Internet is quoting a comparable plan for less. Very price-sensitive after last bill increase; wants a match or they port out.'),
  (29, 'AGT-0005', 'Escalation: repeated outages last month. Says T-Mobile Home Internet ''never goes down'' in their neighborhood. Threatening to switch this week.'),
  (30, 'AGT-0006', 'Moving to a new address and already checked Verizon 5G Home availability there. Asked what we can do to keep the account.'),
  (31, 'AGT-0007', 'Customer called ready to cancel — T-Mobile Home Internet is quoting a comparable plan for less. Very price-sensitive after last bill increase; wants a match or they port out.'),
  (32, 'AGT-0008', 'Cord-cutting conversation — wants internet-only. Saw a AT&T Fiber bundle ad. Considering the offer we presented.'),
  (33, 'AGT-0001', 'Cord-cutting conversation — wants internet-only. Saw a Verizon 5G Home bundle ad. Considering the offer we presented.'),
  (33, 'AGT-0001', 'Customer called ready to cancel — Verizon 5G Home is quoting a comparable plan for less. Very price-sensitive after last bill increase; wants a match or they port out.'),
  (34, 'AGT-0002', 'Cord-cutting conversation — wants internet-only. Saw a Google Fiber bundle ad. Considering the offer we presented.'),
  (35, 'AGT-0003', 'Cord-cutting conversation — wants internet-only. Saw a Verizon 5G Home bundle ad. Considering the offer we presented.'),
  (35, 'AGT-0003', 'Retention call. Customer actively comparing us to Verizon 5G Home. Loyal but frustrated with speed; open to a 12-month promo if we beat Verizon 5G Home.'),
  (36, 'AGT-0004', 'Customer called ready to cancel — T-Mobile Home Internet is quoting a comparable plan for less. Very price-sensitive after last bill increase; wants a match or they port out.'),
  (37, 'AGT-0005', 'Moving to a new address and already checked AT&T Fiber availability there. Asked what we can do to keep the account.'),
  (37, 'AGT-0005', 'Retention call. Customer actively comparing us to AT&T Fiber. Loyal but frustrated with speed; open to a 12-month promo if we beat AT&T Fiber.'),
  (38, 'AGT-0006', 'Customer''s spouse works from home; AT&T Fiber pitched a work-from-home tier. Wants reliability guarantees before renewing.'),
  (38, 'AGT-0006', 'Retention call. Customer actively comparing us to AT&T Fiber. Loyal but frustrated with speed; open to a 12-month promo if we beat AT&T Fiber.'),
  (39, 'AGT-0007', 'Cord-cutting conversation — wants internet-only. Saw a T-Mobile Home Internet bundle ad. Considering the offer we presented.'),
  (40, 'AGT-0008', 'Escalation: repeated outages last month. Says Verizon 5G Home ''never goes down'' in their neighborhood. Threatening to switch this week.'),
  (40, 'AGT-0008', 'Customer''s spouse works from home; Verizon 5G Home pitched a work-from-home tier. Wants reliability guarantees before renewing.');

INSERT INTO ops.offers_presented (case_id, offer_id, offer_name, accepted) VALUES
  (2, 'OFF-03', '12-Month Price Lock', true),
  (3, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (7, 'OFF-03', '12-Month Price Lock', true),
  (11, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (12, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (13, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (15, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (16, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (17, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (18, 'OFF-01', 'TelcoABC One Bundle $49.99', true),
  (19, 'OFF-03', '12-Month Price Lock', false),
  (20, 'OFF-03', '12-Month Price Lock', false),
  (21, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (22, 'OFF-01', 'TelcoABC One Bundle $49.99', true),
  (24, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (25, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (29, 'OFF-01', 'TelcoABC One Bundle $49.99', true),
  (30, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (31, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (32, 'OFF-03', '12-Month Price Lock', false),
  (33, 'OFF-01', 'TelcoABC One Bundle $49.99', false),
  (35, 'OFF-01', 'TelcoABC One Bundle $49.99', true),
  (37, 'OFF-03', '12-Month Price Lock', false),
  (38, 'OFF-03', '12-Month Price Lock', false),
  (39, 'OFF-01', 'TelcoABC One Bundle $49.99', false);

